/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gestionar_Caja;

import Componentes.Mensajes; 
import Componentes.conectar;
import Gestiona_articulo.iFDescripcionArticulos;

import java.awt.Frame; 
import java.awt.event.ActionEvent; 
import java.awt.event.MouseEvent; 
import java.awt.event.WindowEvent; 
import javax.swing.JButton; 
import javax.swing.JDialog; 
import javax.swing.JLabel; 
import javax.swing.JScrollPane; 
import javax.swing.JTable; 
import javax.swing.JTextField;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luca
 */
public class dlgConSalida extends javax.swing.JDialog {
DefaultTableModel model;

    /**
     * Creates new form dlgConSalida
     */
    public dlgConSalida(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargar("");
        tablasalida();
        titulosdetallSalida();
    }

  void cargar(String valor){
    String mostrar="Select * from Salidas order by sal_codigo";
    String titulos[] = {"Cod Salida", "Fecha", "Monto"};
    String []Registros=new String[5];
    model = new DefaultTableModel(null,titulos);
  
        try {
              Statement st = cn.createStatement();
              ResultSet rs = st.executeQuery(mostrar);
              while(rs.next())
              {
                  Registros[0]= rs.getString("sal_codigo");
                  Registros[1]= rs.getString("sal_fecha");
                  Registros[2]= rs.getString("sal_monto");
                       model.addRow(Registros);
              }
              grillaSalidas.setModel(model);
              
        } catch (SQLException ex) {
            Logger.getLogger(iFDescripcionArticulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    
  }  
    
     void tablasalida(){
        // Genera espacion entre las columnas 
         grillaSalidas.getColumnModel().getColumn(0).setPreferredWidth(60);
         grillaSalidas.getColumnModel().getColumn(1).setPreferredWidth(100);
         grillaSalidas.getColumnModel().getColumn(2).setPreferredWidth(150);
     }
     
          void tabladetallesalida(){
        // Genera espacion entre las columnas 
         grillaDetalleSalida.getColumnModel().getColumn(0).setPreferredWidth(70);
         grillaDetalleSalida.getColumnModel().getColumn(1).setPreferredWidth(55);
         grillaDetalleSalida.getColumnModel().getColumn(2).setPreferredWidth(55);
         grillaDetalleSalida.getColumnModel().getColumn(3).setPreferredWidth(210);
        grillaDetalleSalida.getColumnModel().getColumn(4).setPreferredWidth(80);
     }
     
    void titulosdetallSalida(){
        String titulosdet[] = {"Motivo", "Cant.", "Cod", "Descripcion", "Precio"};
        model = new DefaultTableModel(null,titulosdet);
        grillaDetalleSalida.setModel(model);
    }
          
     void cargarDetalleSalida(String valor){
    String mos="Select * FROM (detalle_salida JOIN articulo ON ((detalle_salida.ds_articulo = articulo.art_codigo)))   JOIN motivo ON ((detalle_salida.ds_motivo = motivo.mot_codigo)) JOIN salidas ON ((detalle_salida.ds_salida = salidas.sal_codigo)) WHERE (salidas.sal_codigo) like '%"+valor+"%'";
    String titulosdet[] = {"Motivo", "Cant.", "Cod", "Descripcion", "Precio"};
    String []Registros=new String[20];
    model = new DefaultTableModel(null,titulosdet);
  
        try {
              Statement st = cn.createStatement();
              ResultSet rs = st.executeQuery(mos);
              while(rs.next())
              {
                  Registros[0]= rs.getString("motivo.mot_nombre");
                  Registros[1]= rs.getString("detalle_salida.ds_cantidad");
                  Registros[2]= rs.getString("detalle_salida.ds_salida");
                  Registros[3]= rs.getString("articulo.art_descripcion");                  
                  Registros[4]= rs.getString("detalle_salida.ds_precio");
                 
               
                  model.addRow(Registros);
              }
              grillaDetalleSalida.setModel(model);

        } catch (SQLException ex) {
            Logger.getLogger(dlgConSalida.class.getName()).log(Level.SEVERE, null, ex);
        }
                
                 
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        grillaSalidas = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowInddex, int celIndex)
            {
                return false;
            }
        };
        jScrollPane2 = new javax.swing.JScrollPane();
        grillaDetalleSalida = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowInddex, int celIndex)
            {
                return false;
            }
        };
        Salir = new javax.swing.JButton();
        txtFecha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        grillaSalidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        grillaSalidas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        grillaSalidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grillaSalidasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grillaSalidas);

        grillaDetalleSalida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title", "Title", "Title", "Title", "Title"
            }
        ));
        grillaDetalleSalida.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(grillaDetalleSalida);

        Salir.setText("Salir");
        Salir.setToolTipText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        txtFecha.setEditable(false);

        jLabel1.setText("Fecha :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFecha)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Salir)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grillaSalidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grillaSalidasMouseClicked
        int fila= grillaSalidas.getSelectedRow();
         try {
           if(fila>=0){
        String codigo = grillaSalidas.getValueAt(fila, 0).toString();
        String fecha = grillaSalidas.getValueAt(fila, 1).toString();
        txtFecha.setText(fecha);
       
       cargarDetalleSalida(codigo);
       tabladetallesalida();         
           }
         
         
         }
                     catch (Exception e) {
            
            }
    }//GEN-LAST:event_grillaSalidasMouseClicked

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgConSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgConSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgConSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgConSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgConSalida dialog = new dlgConSalida(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JTable grillaDetalleSalida;
    public static javax.swing.JTable grillaSalidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables

conectar cc= new conectar();
Connection cn= cc.conexion();

}
