/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import Componentes.Fondo;
import Componentes.Mensajes;
import Componentes.Reloj;
import Formularios.Gestionar_Ventas.IF_FacturaVenta;
import Formularios.Gestionar_Ventas.If_Factura;
import Formularios.Gestionar_Ventas.JDlg_BuscarArticuloVta;
import Formularios.Gestionar_Ventas.JDlg_Factura;
import Formularios.dlgNotas;
import Gestiona_articulo.iFDescripcionArticulos;
import Gestionar_Caja.dlgConsultarEgresos;
import Gestionar_Caja.dlgConsultarIngresos;
import Gestionar_Caja.dlgMovimientoCajaegr;
import Gestionar_Caja.dlgMovimientoCajaing;

import Gestionar_Caja.iFCaja;
import Gestionar_Caja.If_Ingreso;
import Gestionar_Caja.If_Gastos;
import Gestionar_Empleado.iFDescripcionEmpleado26;
import Gestionar_Clientes.iFDescripcionClientes;
import Gestionar_Empleado.iFDescripcionEmpleado;
import Gestionar_Proveedores.iFDescripcionProveedor;
import Gestionar_compra.iF_CargaCompra;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Gaston
 */
public class NewJFrame extends javax.swing.JFrame {
    public InputStream foto1=this.getClass().getResourceAsStream("/imag_inicio/LaPuntual11_opt.jpg");

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
         smallMenu();
//          reloj();
         cargarImagen(Escritorio, foto1);
         this.setExtendedState(NewJFrame.MAXIMIZED_BOTH);
//         abrirCaja();
        iconoFormulario();
    }
    
    public void iconoFormulario(){
        
        URL url = getClass().getResource("/menu/icono_del_sistema_1.jpg");
        ImageIcon icono = new ImageIcon(url);
        setIconImage(icono.getImage());
        
    }
    
    void reloj(){
        Reloj hilo = new Reloj(lblReloj, lblFecha);
          hilo.start();
    }

     void cargarImagen(javax.swing.JDesktopPane jDeskp,InputStream fileImagen)
    {   
        try{   
            BufferedImage image = ImageIO.read(fileImagen);        
              jDeskp.setBorder(new Fondo(image)); }
        catch (Exception e){   System.out.println("Imagen no disponible");   }        
    }
     
//       void abrirCaja() {
//   
//             iFCaja caja=new iFCaja();
//             Escritorio.add(caja);
//             caja.setTitle("Arqueo de caja");
//             caja.setVisible(true);
//              
//           
//    }
     public  void CentrarVentanaInterna(JInternalFrame internalframe){ 
           int x = (Escritorio.getWidth()/2)- internalframe.getWidth()/2; // Calculamos la posicion de l apantalla
           int y = (Escritorio.getHeight()/2)- internalframe.getHeight()/2;
           
           if (internalframe.isShowing()){ // preguntamos si la ventana esta ejecutada
               internalframe.setLocation(x, y);
           } else{
               Escritorio.add(internalframe);
               internalframe.setLocation(x, y);//si es asi solo lo colocamos en la mitad
               internalframe.show();
           }
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     
//       if (jToggleButton_BD.isSelected()) {
//      //Menu 1
//      panel_BD.setSize(210, 180);
//      //Menu 2
//      panel_Ingre.setLocation(0, 190);
//      panel_Ingre.setSize(210, 50);           
//      jToggleButton_Ingre.setSelected(false);      
//      //menu 3
//      panel_Egres.setLocation(0, 240);
//      panel_Egres.setSize(210, 50);           
//      jToggleButton_Egres.setSelected(false);
//      //menu 4
//       panel_herramientas.setLocation(0, 290);
//       panel_herramientas.setSize(210, 50);
//       jToggleButton_Herram.setSelected(false);
//      //menu 5
//       panel_tesoreria.setLocation(0, 340);
//       panel_tesoreria.setSize(210, 50);
//       jToggleButton_tesoreria.setSelected(false);
//      //menu 6
//       panel_Informes.setLocation(0, 390);
//       panel_Informes.setSize(210, 50);
//       jToggleButton_informes.setSelected(false);   
//  }
//  else {
//      smallMenu();
//  }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        panel_BD = new javax.swing.JPanel();
        jToggleButton_BD = new javax.swing.JToggleButton();
        bto_Empleados = new javax.swing.JButton();
        bto_Clientes = new javax.swing.JButton();
        bto_Proveedor = new javax.swing.JButton();
        bto_Articulos = new javax.swing.JButton();
        panel_Ingre = new javax.swing.JPanel();
        jToggleButton_Ingre = new javax.swing.JToggleButton();
        bto_otrosIngr = new javax.swing.JButton();
        bto_vtas = new javax.swing.JButton();
        bto_presupuesto = new javax.swing.JButton();
        panel_Egres = new javax.swing.JPanel();
        jToggleButton_Egres = new javax.swing.JToggleButton();
        bto_gastos = new javax.swing.JButton();
        bto_compras = new javax.swing.JButton();
        panel_Informes = new javax.swing.JPanel();
        jToggleButton_informes = new javax.swing.JToggleButton();
        panel_herramientas = new javax.swing.JPanel();
        jToggleButton_Herram = new javax.swing.JToggleButton();
        jButton6 = new javax.swing.JButton();
        bto_Notas = new javax.swing.JButton();
        bto_calculadora = new javax.swing.JButton();
        panel_tesoreria = new javax.swing.JPanel();
        jToggleButton_tesoreria = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Escritorio = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        lblReloj = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        menu.setBackground(new java.awt.Color(153, 153, 153));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_BD.setBackground(new java.awt.Color(153, 153, 153));

        jToggleButton_BD.setBackground(new java.awt.Color(102, 102, 102));
        jToggleButton_BD.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton_BD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/icons8_Add_User_Group_Woman_Man_35px.png"))); // NOI18N
        jToggleButton_BD.setText("Base de Datos");
        jToggleButton_BD.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jToggleButton_BD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButton_BD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_BDActionPerformed(evt);
            }
        });

        bto_Empleados.setText("Empleados");
        bto_Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_EmpleadosActionPerformed(evt);
            }
        });

        bto_Clientes.setText("Clientes");
        bto_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_ClientesActionPerformed(evt);
            }
        });

        bto_Proveedor.setText("Proveedores");
        bto_Proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_ProveedorActionPerformed(evt);
            }
        });

        bto_Articulos.setText("Articulos");
        bto_Articulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_ArticulosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_BDLayout = new javax.swing.GroupLayout(panel_BD);
        panel_BD.setLayout(panel_BDLayout);
        panel_BDLayout.setHorizontalGroup(
            panel_BDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BDLayout.createSequentialGroup()
                .addGroup(panel_BDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bto_Empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bto_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bto_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bto_Articulos, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton_BD, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_BDLayout.setVerticalGroup(
            panel_BDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BDLayout.createSequentialGroup()
                .addComponent(jToggleButton_BD, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bto_Empleados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bto_Clientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bto_Proveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bto_Articulos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu.add(panel_BD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 50));

        panel_Ingre.setBackground(new java.awt.Color(153, 153, 153));

        jToggleButton_Ingre.setBackground(new java.awt.Color(102, 102, 102));
        jToggleButton_Ingre.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton_Ingre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/icons8_Add_Shopping_Cart_35px.png"))); // NOI18N
        jToggleButton_Ingre.setText("Ingresos ");
        jToggleButton_Ingre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButton_Ingre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_IngreActionPerformed(evt);
            }
        });

        bto_otrosIngr.setText("Otros Ingresos");
        bto_otrosIngr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_otrosIngrActionPerformed(evt);
            }
        });

        bto_vtas.setText("Ventas");
        bto_vtas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_vtasActionPerformed(evt);
            }
        });

        bto_presupuesto.setText("Presupuesto");

        javax.swing.GroupLayout panel_IngreLayout = new javax.swing.GroupLayout(panel_Ingre);
        panel_Ingre.setLayout(panel_IngreLayout);
        panel_IngreLayout.setHorizontalGroup(
            panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_IngreLayout.createSequentialGroup()
                .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bto_vtas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bto_otrosIngr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton_Ingre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(bto_presupuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_IngreLayout.setVerticalGroup(
            panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_IngreLayout.createSequentialGroup()
                .addComponent(jToggleButton_Ingre, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(bto_otrosIngr)
                .addGap(6, 6, 6)
                .addComponent(bto_vtas)
                .addGap(6, 6, 6)
                .addComponent(bto_presupuesto))
        );

        menu.add(panel_Ingre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 190, 50));

        panel_Egres.setBackground(new java.awt.Color(153, 153, 153));

        jToggleButton_Egres.setBackground(new java.awt.Color(102, 102, 102));
        jToggleButton_Egres.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton_Egres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/icons8_Move_Stock_35px.png"))); // NOI18N
        jToggleButton_Egres.setText("Egresos");
        jToggleButton_Egres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButton_Egres.setMaximumSize(new java.awt.Dimension(77, 23));
        jToggleButton_Egres.setMinimumSize(new java.awt.Dimension(77, 23));
        jToggleButton_Egres.setPreferredSize(new java.awt.Dimension(77, 23));
        jToggleButton_Egres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_EgresActionPerformed(evt);
            }
        });

        bto_gastos.setText("Gastos");
        bto_gastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_gastosActionPerformed(evt);
            }
        });

        bto_compras.setText("Compras");
        bto_compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_comprasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_EgresLayout = new javax.swing.GroupLayout(panel_Egres);
        panel_Egres.setLayout(panel_EgresLayout);
        panel_EgresLayout.setHorizontalGroup(
            panel_EgresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_EgresLayout.createSequentialGroup()
                .addGroup(panel_EgresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bto_gastos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton_Egres, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(bto_compras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_EgresLayout.setVerticalGroup(
            panel_EgresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_EgresLayout.createSequentialGroup()
                .addComponent(jToggleButton_Egres, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(bto_gastos)
                .addGap(7, 7, 7)
                .addComponent(bto_compras))
        );

        menu.add(panel_Egres, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 190, 50));

        panel_Informes.setBackground(new java.awt.Color(153, 153, 153));

        jToggleButton_informes.setBackground(new java.awt.Color(102, 102, 102));
        jToggleButton_informes.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton_informes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/icons8_Report_Card_35px.png"))); // NOI18N
        jToggleButton_informes.setText("Informes");
        jToggleButton_informes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButton_informes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_informesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_InformesLayout = new javax.swing.GroupLayout(panel_Informes);
        panel_Informes.setLayout(panel_InformesLayout);
        panel_InformesLayout.setHorizontalGroup(
            panel_InformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_InformesLayout.createSequentialGroup()
                .addComponent(jToggleButton_informes, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        panel_InformesLayout.setVerticalGroup(
            panel_InformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_InformesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jToggleButton_informes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menu.add(panel_Informes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 190, 50));

        panel_herramientas.setBackground(new java.awt.Color(153, 153, 153));

        jToggleButton_Herram.setBackground(new java.awt.Color(102, 102, 102));
        jToggleButton_Herram.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton_Herram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/icons8_Maintenance_35px.png"))); // NOI18N
        jToggleButton_Herram.setText("Herramientas");
        jToggleButton_Herram.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButton_Herram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_HerramActionPerformed(evt);
            }
        });

        jButton6.setText("Calendario");

        bto_Notas.setText("Notas");
        bto_Notas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_NotasActionPerformed(evt);
            }
        });

        bto_calculadora.setText("Calculadora");
        bto_calculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_calculadoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_herramientasLayout = new javax.swing.GroupLayout(panel_herramientas);
        panel_herramientas.setLayout(panel_herramientasLayout);
        panel_herramientasLayout.setHorizontalGroup(
            panel_herramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_herramientasLayout.createSequentialGroup()
                .addGroup(panel_herramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bto_Notas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton_Herram, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(bto_calculadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_herramientasLayout.setVerticalGroup(
            panel_herramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_herramientasLayout.createSequentialGroup()
                .addComponent(jToggleButton_Herram, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addGap(7, 7, 7)
                .addComponent(bto_Notas)
                .addGap(7, 7, 7)
                .addComponent(bto_calculadora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu.add(panel_herramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 190, 50));

        panel_tesoreria.setBackground(new java.awt.Color(153, 153, 153));

        jToggleButton_tesoreria.setBackground(new java.awt.Color(102, 102, 102));
        jToggleButton_tesoreria.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton_tesoreria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/icons8_Cash_Counter_35px.png"))); // NOI18N
        jToggleButton_tesoreria.setText("Tesoreria");
        jToggleButton_tesoreria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButton_tesoreria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_tesoreriaActionPerformed(evt);
            }
        });

        jButton2.setText("Ingresos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Egresos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Consulta Caja");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_tesoreriaLayout = new javax.swing.GroupLayout(panel_tesoreria);
        panel_tesoreria.setLayout(panel_tesoreriaLayout);
        panel_tesoreriaLayout.setHorizontalGroup(
            panel_tesoreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tesoreriaLayout.createSequentialGroup()
                .addGroup(panel_tesoreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton_tesoreria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_tesoreriaLayout.setVerticalGroup(
            panel_tesoreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tesoreriaLayout.createSequentialGroup()
                .addComponent(jToggleButton_tesoreria, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(7, 7, 7)
                .addComponent(jButton1)
                .addGap(7, 7, 7)
                .addComponent(jButton3))
        );

        menu.add(panel_tesoreria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 190, 50));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1011, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lblFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(204, 204, 204));

        lblReloj.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblReloj.setForeground(new java.awt.Color(204, 204, 204));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos50/icons8_Minus_28px_1_1.png"))); // NOI18N
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusPainted(false);
        jButton7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos50/icons8_Minus_28px_2.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos50/icons8_Cancel_28px_1.png"))); // NOI18N
        jButton8.setContentAreaFilled(false);
        jButton8.setFocusable(false);
        jButton8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos50/icons8_Cancel_28px_4.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(334, 334, 334)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Escritorio))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addComponent(Escritorio)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton_BDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_BDActionPerformed

        
        
        if (jToggleButton_BD.isSelected()) {
      //Menu 1
      panel_BD.setSize(210, 180);
      //Menu 2
      panel_Ingre.setLocation(0, 190);
      panel_Ingre.setSize(210, 50);           
      jToggleButton_Ingre.setSelected(false);      
      //menu 3
      panel_Egres.setLocation(0, 240);
      panel_Egres.setSize(210, 50);           
      jToggleButton_Egres.setSelected(false);
      //menu 4
       panel_herramientas.setLocation(0, 290);
       panel_herramientas.setSize(210, 50);
       jToggleButton_Herram.setSelected(false);
      //menu 5
       panel_tesoreria.setLocation(0, 340);
       panel_tesoreria.setSize(210, 50);
       jToggleButton_tesoreria.setSelected(false);
      //menu 6
       panel_Informes.setLocation(0, 390);
       panel_Informes.setSize(210, 50);
       jToggleButton_informes.setSelected(false);   
       
       
  }
  else {
      smallMenu();
  }

    }//GEN-LAST:event_jToggleButton_BDActionPerformed

    private void jToggleButton_IngreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_IngreActionPerformed
        if (jToggleButton_Ingre.isSelected()) {
       //Menu 1
       panel_BD.setSize(210, 50);
       jToggleButton_BD.setSelected(false); 
       //Menu 2
       panel_Ingre.setLocation(0, 50);
       panel_Ingre.setSize(210, 150);  
       //menu 3
       panel_Egres.setLocation(0, 210);
       panel_Egres.setSize(210, 50);           
       jToggleButton_Egres.setSelected(false);
       //menu 4
       panel_herramientas.setLocation(0, 260);
       panel_herramientas.setSize(210, 50);
       jToggleButton_Herram.setSelected(false);
      //menu 5
       panel_tesoreria.setLocation(0, 310);
       panel_tesoreria.setSize(210, 50);
       jToggleButton_tesoreria.setSelected(false); 
     //menu 6
       panel_Informes.setLocation(0, 360);
       panel_Informes.setSize(210, 50);
       jToggleButton_informes.setSelected(false);    
       
   }
   else {
       smallMenu();
   }
    }//GEN-LAST:event_jToggleButton_IngreActionPerformed

    private void jToggleButton_EgresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_EgresActionPerformed
           if (jToggleButton_Egres.isSelected()) {
       //Menu 1
       panel_BD.setSize(210, 50);
       jToggleButton_BD.setSelected(false); 
       //Menu 2
       panel_Ingre.setSize(210, 50);  
       panel_Ingre.setLocation(0, 50);
       jToggleButton_Ingre.setSelected(false);
       //menu 3
       panel_Egres.setLocation(0, 100);
       panel_Egres.setSize(210, 120);  
       //menu 4
       panel_herramientas.setLocation(0, 220);
       panel_herramientas.setSize(210, 50);
       jToggleButton_Herram.setSelected(false);
       //menu 5
       panel_tesoreria.setLocation(0, 270);
       panel_tesoreria.setSize(210, 50);
       jToggleButton_tesoreria.setSelected(false);     
       //menu 6
       panel_Informes.setLocation(0, 320);
       panel_Informes.setSize(210, 50);
       jToggleButton_informes.setSelected(false);   
   }
   else {
       smallMenu();
           }
   
    }//GEN-LAST:event_jToggleButton_EgresActionPerformed

    private void jToggleButton_HerramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_HerramActionPerformed
         if (jToggleButton_Herram.isSelected()) {
            //Menu 1
            panel_BD.setSize(210, 50);
            jToggleButton_BD.setSelected(false);
            //Menu 2
            panel_Ingre.setSize(210, 50);
            panel_Ingre.setLocation(0, 50);
            jToggleButton_Ingre.setSelected(false);
            //menu 3
            panel_Egres.setLocation(0, 100);
            panel_Egres.setSize(210, 50);
            jToggleButton_Egres.setSelected(false);
            //menu 4
            panel_herramientas.setLocation(0, 150);
            panel_herramientas.setSize(210, 150);
            //menu 5
            panel_tesoreria.setLocation(0, 305);
            panel_tesoreria.setSize(210, 50);
            jToggleButton_tesoreria.setSelected(false); 
          //menu 6
           panel_Informes.setLocation(0, 355);
           panel_Informes.setSize(210, 50);
           jToggleButton_informes.setSelected(false);  
           
        } else {
            smallMenu();
        }
    }//GEN-LAST:event_jToggleButton_HerramActionPerformed

    private void jToggleButton_tesoreriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_tesoreriaActionPerformed
        
        if (jToggleButton_tesoreria.isSelected()) {
            //Menu 1
            panel_BD.setSize(210, 50);
            jToggleButton_BD.setSelected(false);
            //Menu 2
            panel_Ingre.setSize(210, 50);
            panel_Ingre.setLocation(0, 50);
            jToggleButton_Ingre.setSelected(false);
            //menu 3
            panel_Egres.setLocation(0, 100);
            panel_Egres.setSize(210, 50);
            jToggleButton_Egres.setSelected(false);
            //menu 4
            panel_herramientas.setLocation(0, 150);
            panel_herramientas.setSize(210, 50);
            jToggleButton_Herram.setSelected(false); 
            //menu 5
            panel_tesoreria.setLocation(0, 200);
            panel_tesoreria.setSize(210, 150);
            //menu 6
           panel_Informes.setLocation(0, 350);
           panel_Informes.setSize(210, 50);
           jToggleButton_informes.setSelected(false);
                 
           
        } else {
            smallMenu();
        }
    }//GEN-LAST:event_jToggleButton_tesoreriaActionPerformed

    private void jToggleButton_informesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_informesActionPerformed
         if (jToggleButton_informes.isSelected()) {
            //Menu 1
            panel_BD.setSize(210, 50);
            jToggleButton_BD.setSelected(false);
            //Menu 2
            panel_Ingre.setSize(210, 50);
            panel_Ingre.setLocation(0, 50);
            jToggleButton_Ingre.setSelected(false);
            //menu 3
            panel_Egres.setLocation(0, 100);
            panel_Egres.setSize(210, 50);
            jToggleButton_Egres.setSelected(false);
            //menu 4
            panel_herramientas.setLocation(0, 150);
            panel_herramientas.setSize(210, 50);
            jToggleButton_Herram.setSelected(false); 
            //menu 5
            panel_tesoreria.setLocation(0, 200);
            panel_tesoreria.setSize(210, 50);
            jToggleButton_tesoreria.setSelected(false);
            
            //menu 6
           panel_Informes.setLocation(0, 250);
           panel_Informes.setSize(210, 50);
           
                 
           
        } else {
            smallMenu();
        }
    }//GEN-LAST:event_jToggleButton_informesActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        this.setState(NewJFrame.ICONIFIED);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try{
            int dialogBotoon = JOptionPane.YES_NO_OPTION;
            int result = JOptionPane.showConfirmDialog(null,"Desea salir del Sistema","Exit", dialogBotoon);

            if(result == 0){

                System.exit(0);
            }
        }
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e);
        }

                                  
    }//GEN-LAST:event_jButton8ActionPerformed
    iFDescripcionEmpleado miEmpleado = new iFDescripcionEmpleado();
    private void bto_EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_EmpleadosActionPerformed

        
        
        if(!(miEmpleado instanceof iFDescripcionEmpleado)){
           miEmpleado = new iFDescripcionEmpleado();
           
        } 

        CentrarVentanaInterna(miEmpleado);
    }//GEN-LAST:event_bto_EmpleadosActionPerformed
        iFDescripcionClientes miCliente = new iFDescripcionClientes();
    private void bto_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_ClientesActionPerformed

         if(!(miCliente instanceof iFDescripcionClientes)){
           miCliente = new iFDescripcionClientes();
           
        } 

        CentrarVentanaInterna(miCliente);
        

      
    }//GEN-LAST:event_bto_ClientesActionPerformed
    iFDescripcionProveedor miProv = new iFDescripcionProveedor();
    private void bto_ProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_ProveedorActionPerformed

       if(!(miProv instanceof iFDescripcionProveedor)){
           miProv = new iFDescripcionProveedor();
           
        } 

        CentrarVentanaInterna(miProv);
        
        
    }//GEN-LAST:event_bto_ProveedorActionPerformed
    iFDescripcionArticulos miArt = new iFDescripcionArticulos();
    private void bto_ArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_ArticulosActionPerformed
        
        if(!(miArt instanceof iFDescripcionArticulos)){
           miArt = new iFDescripcionArticulos();
           
        } 

        CentrarVentanaInterna(miArt);
        
        
       
        
    }//GEN-LAST:event_bto_ArticulosActionPerformed
     If_Factura miVta = new If_Factura();
    private void bto_vtasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_vtasActionPerformed
    
        if(!(miVta instanceof If_Factura)){
           miVta = new If_Factura();
           
        } 

        CentrarVentanaInterna(miVta);
        
          
        
    }//GEN-LAST:event_bto_vtasActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowOpened
    iF_CargaCompra miCop = new iF_CargaCompra();
    private void bto_comprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_comprasActionPerformed
            
       if(!(miCop instanceof iF_CargaCompra)){
           miCop = new iF_CargaCompra();
           
        } 

        CentrarVentanaInterna(miCop);
    }//GEN-LAST:event_bto_comprasActionPerformed
    iFCaja miCaja = new iFCaja();
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
         if(!(miCaja instanceof iFCaja)){
           miCaja = new iFCaja();
           
        } 

        CentrarVentanaInterna(miCaja);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

       try {
            dlgMovimientoCajaing miIngr = new dlgMovimientoCajaing();
            miIngr.setLocationRelativeTo(null);
            miIngr.setTitle("nuevo ingreso");
            miIngr.setVisible(true);
        } catch (Exception e) {
            Mensajes.informacion("No hay conexión con el servidor");

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

         try {
             dlgMovimientoCajaegr miEgre = new dlgMovimientoCajaegr();
            miEgre.setLocationRelativeTo(null);
            miEgre.setTitle("nuevo egreso");
            miEgre.setVisible(true);
        } catch (Exception e) {
            Mensajes.informacion("No hay conexión con el servidor");

        }
    }//GEN-LAST:event_jButton1ActionPerformed
     If_Ingreso miIng ;
    private void bto_otrosIngrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_otrosIngrActionPerformed
        if(!(miIng instanceof If_Ingreso)){
           miIng = new If_Ingreso();
           
        } 

        CentrarVentanaInterna(miIng);
        // TODO add your handling code here:
    }//GEN-LAST:event_bto_otrosIngrActionPerformed
     If_Gastos miGas;
    private void bto_gastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_gastosActionPerformed
        if(!(miGas instanceof If_Gastos)){
           miGas = new If_Gastos();
           
        } 

        CentrarVentanaInterna(miGas);
        // TODO add your handling code here:
    }//GEN-LAST:event_bto_gastosActionPerformed

    private void bto_calculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_calculadoraActionPerformed

        // TODO add your handling code here:
               try
        {
            Runtime obj = Runtime.getRuntime();
            obj.exec("C:\\WINDOWS\\system32\\CALC.EXE");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_bto_calculadoraActionPerformed

    private void bto_NotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_NotasActionPerformed
        // TODO add your handling code here:
       dlgNotas notas = new dlgNotas(this, true);
       notas.setLocationRelativeTo(null);
       notas.setVisible(true);
       notas.setTitle("Notas");
    }//GEN-LAST:event_bto_NotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JButton bto_Articulos;
    private javax.swing.JButton bto_Clientes;
    private javax.swing.JButton bto_Empleados;
    private javax.swing.JButton bto_Notas;
    private javax.swing.JButton bto_Proveedor;
    private javax.swing.JButton bto_calculadora;
    private javax.swing.JButton bto_compras;
    private javax.swing.JButton bto_gastos;
    private javax.swing.JButton bto_otrosIngr;
    private javax.swing.JButton bto_presupuesto;
    private javax.swing.JButton bto_vtas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton_BD;
    private javax.swing.JToggleButton jToggleButton_Egres;
    private javax.swing.JToggleButton jToggleButton_Herram;
    private javax.swing.JToggleButton jToggleButton_Ingre;
    private javax.swing.JToggleButton jToggleButton_informes;
    private javax.swing.JToggleButton jToggleButton_tesoreria;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblReloj;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel panel_BD;
    private javax.swing.JPanel panel_Egres;
    private javax.swing.JPanel panel_Informes;
    private javax.swing.JPanel panel_Ingre;
    private javax.swing.JPanel panel_herramientas;
    private javax.swing.JPanel panel_tesoreria;
    // End of variables declaration//GEN-END:variables

public void smallMenu() {
   //Menu 1
   panel_BD.setSize(210, 50);
   jToggleButton_BD.setSelected(false);
  
   //Menu 2
   panel_Ingre.setLocation(0, 50);
   panel_Ingre.setSize(210, 50);            
   jToggleButton_Ingre.setSelected(false);
   //Menu 3
   panel_Egres.setLocation(0, 100);
   panel_Egres.setSize(210, 50);
   jToggleButton_Egres.setSelected(false);
   //menu 4
   panel_herramientas.setLocation(0, 150);
   panel_herramientas.setSize(210, 50);
   jToggleButton_Herram.setSelected(false);
   //menu 5
   panel_tesoreria.setLocation(0, 200);
   panel_tesoreria.setSize(210, 50);
   jToggleButton_tesoreria.setSelected(false);
  //menu 6
   panel_Informes.setLocation(0, 250);
   panel_Informes.setSize(210, 50);
   jToggleButton_informes.setSelected(false); 
   
} 

}

