/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Clases.Usuario;
import Componentes.Fondo;
import Componentes.Mensajes;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Gaston
 */
public class jDlg_Registrarse extends javax.swing.JDialog {
    /**
     * Creates new form jDlg_Registrarse
     */
    public jDlg_Registrarse(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
    }
    Usuario miUsuario = new Usuario();
    
     void LimpiarCampos()
    {
        txt_ConfirmarPass.setText("");
        txt_pass.setText("");
        txt_Reg_nombre.setText("");
        txt_Reg_apellido.setText("");
        txt_respSecre.setText("");
        txt_Reg_nombre_usuario.setText("");
       
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_Reg_nombre = new javax.swing.JTextField();
        txt_Reg_apellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_Reg_nombre_usuario = new javax.swing.JTextField();
        cbo_PregSecre = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_respSecre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bto_cancelar = new javax.swing.JButton();
        bto_aceptar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        txt_ConfirmarPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre de usuario:");

        jLabel10.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Registrar Usuario:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido:");

        cbo_PregSecre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre de mi mascota ", "Nombre de un idolo ", "Lugar de nacimiento", "Lugar de nacimiento de la madre", "Lugar de nacimiento de la padre", " " }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pregunta Secreta:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Respuesta:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Repite Contraseña:");

        bto_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-atras_opt.png"))); // NOI18N
        bto_cancelar.setToolTipText("Cancelar");
        bto_cancelar.setBorderPainted(false);
        bto_cancelar.setContentAreaFilled(false);
        bto_cancelar.setFocusPainted(false);
        bto_cancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-atras_opt (1).png"))); // NOI18N
        bto_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_cancelarActionPerformed(evt);
            }
        });

        bto_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-guardar_opt (1).png"))); // NOI18N
        bto_aceptar.setToolTipText("Guardar Usuario");
        bto_aceptar.setBorderPainted(false);
        bto_aceptar.setContentAreaFilled(false);
        bto_aceptar.setFocusPainted(false);
        bto_aceptar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-guardar_opt.png"))); // NOI18N
        bto_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_aceptarActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_ABM/orig_60533_1.jpg"))); // NOI18N

        txt_ConfirmarPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_ConfirmarPassKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bto_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_Reg_nombre_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                        .addComponent(txt_Reg_apellido, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                        .addComponent(txt_Reg_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                        .addComponent(txt_respSecre, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                        .addComponent(cbo_PregSecre, 0, 255, Short.MAX_VALUE)
                        .addComponent(txt_pass)
                        .addComponent(txt_ConfirmarPass))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(bto_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 420, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bto_aceptar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txt_Reg_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(txt_Reg_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Reg_nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbo_PregSecre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_respSecre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_ConfirmarPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(bto_cancelar)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 473, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bto_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_aceptarActionPerformed

              
               GestionarUsuario GuardarUsuario = new GestionarUsuario();
        
                if(txt_Reg_nombre.getText().isEmpty() )                                                                                                   //VALIDACIONES
               {
                       JOptionPane.showMessageDialog(null,"Igrese NOMBRE ","Error: Datos Incompletos",JOptionPane.ERROR_MESSAGE);
            
                   }
                if(txt_Reg_apellido.getText().isEmpty() )                                                                                                   //VALIDACIONES
               {
                       JOptionPane.showMessageDialog(null,"Igrese APELLIDO ","Error: Datos Incompletos",JOptionPane.ERROR_MESSAGE);
            
                   }
        
                    if(txt_Reg_nombre_usuario.getText().isEmpty() )                                                                                                   //VALIDACIONES
               {
                       JOptionPane.showMessageDialog(null,"Igrese NOMBRE DE USUARIO ","Error: Datos Incompletos",JOptionPane.ERROR_MESSAGE);
            
                   }
               else if(txt_pass.getText().isEmpty() )
                {
                        JOptionPane.showMessageDialog(null," Ingrese una CONTRASEÑA ","Error: Datos Incompletos",JOptionPane.ERROR_MESSAGE);
                    }
        
               else  if(txt_ConfirmarPass.getText().isEmpty() )
                {
                        JOptionPane.showMessageDialog(null,"REPITE CONTRAEÑA ","Error: Datos Incompletos",JOptionPane.ERROR_MESSAGE);
                    }
        
                   else  if(cbo_PregSecre.getSelectedIndex()==-1)
                {
                        JOptionPane.showMessageDialog(null,"SELECCIONE Pregunta Secreta ","Error: Datos Incompletos",JOptionPane.ERROR_MESSAGE);
                    }
               else if(txt_respSecre.getText().isEmpty() )
               {
                       JOptionPane.showMessageDialog(null,"Igrese Respueta Secreta ","Error: Datos Incompletos",JOptionPane.ERROR_MESSAGE);
            
                   }
              
               else{
            
            
            
            
                          miUsuario.setNombre(txt_Reg_nombre.getText().toUpperCase());
                          miUsuario.setApellido(txt_Reg_apellido.getText().toUpperCase());
                          miUsuario.setNombreUsuario(txt_Reg_nombre_usuario.getText().toUpperCase());
                          miUsuario.setContraseña(String.valueOf(txt_pass.getPassword()));
                          String contra =(String.valueOf(txt_ConfirmarPass.getPassword()));
                          
            
                         
            
                        miUsuario.setTipoRespSecre( String.valueOf(cbo_PregSecre.getSelectedItem()));
                     
            
                        miUsuario.setRespuesta(txt_respSecre.getText().toUpperCase());
            
            
            
                        GuardarUsuario.GuardarUsuario(miUsuario);
            
                        Mensajes.informacion("Usuario Registrado");
                       
                       LimpiarCampos();
            
            
                    }

    }//GEN-LAST:event_bto_aceptarActionPerformed

    private void txt_ConfirmarPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ConfirmarPassKeyReleased
        String contra1= String.valueOf(txt_pass.getPassword());
        String contra2= String.valueOf(txt_ConfirmarPass.getPassword());
        if(contra1.equals(contra2)){
            
            txt_ConfirmarPass.setForeground(Color.GREEN);
            bto_aceptar.setEnabled(true);
        }else{
             txt_ConfirmarPass.setForeground(Color.RED);
            bto_aceptar.setEnabled(false);
        }
    }//GEN-LAST:event_txt_ConfirmarPassKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        // TODO add your handling code here:
         bto_aceptar.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void bto_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bto_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDlg_Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDlg_Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDlg_Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDlg_Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jDlg_Registrarse dialog = new jDlg_Registrarse(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bto_aceptar;
    private javax.swing.JButton bto_cancelar;
    private javax.swing.JComboBox<String> cbo_PregSecre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField txt_ConfirmarPass;
    private javax.swing.JTextField txt_Reg_apellido;
    private javax.swing.JTextField txt_Reg_nombre;
    private javax.swing.JTextField txt_Reg_nombre_usuario;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_respSecre;
    // End of variables declaration//GEN-END:variables
}
