/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Componentes.conectar;
import Metodos.Conectar;
import com.sun.awt.AWTUtilities;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

import menu.NewJFrame;

/**
 *
 * @author Gaston
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    conectar miconexion = new conectar();
    Connection con = miconexion.conexion();

    //algoritmos
    public static String MD2 = "MD2";
    public static String MD5 = "MD5";
    public static String SHA1 = "SHA-1";
    public static String SHA256 = "SHA-256";
    public static String SHA384 = "SHA-384";
    public static String SHA512 = "SHA-512";

    String id[] = new String[50];
    static int intContador;
    int intentos = 0;
    public String codigo;
    String usu, pass;
    static Connection conn = null;
    static ResultSet rs = null;
    static ResultSet rs1 = null;

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this, false);
    }

    int x, y;

    private static String toHexadecimal(byte[] digest) {
        String hash = "";
        for (byte aux : digest) {
            int b = aux & 0xff;
            if (Integer.toHexString(b).length() == 1) {
                hash += "0";
            }
            hash += Integer.toHexString(b);
        }
        return hash;
    }

    public static String getStringMessageDigest(String message, String algorithm) {
        byte[] digest = null;
        byte[] buffer = message.getBytes();
        try {
            MessageDigest messageDigest = MessageDigest.getInstance(algorithm);
            messageDigest.reset();
            messageDigest.update(buffer);
            digest = messageDigest.digest();
        } catch (NoSuchAlgorithmException ex) {
            System.out.println("Error creando Digest");
        }
        return toHexadecimal(digest);
    }

    public void ValidarAcceso() {

        int resultado = 0;

        try {

            String usuario = txt_usuario.getText();
            String pass = String.valueOf(txt_contraseña.getPassword());
            
            String sql = "select * from usuario where nombreUsuario='" + usuario + "' and contraseña='" + pass + "'";

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {

                resultado = 1;

                if (resultado == 1) {
                    Iniciando_v1 mdi = new Iniciando_v1();
                    mdi.show();
                    mdi.setVisible(true);
                    this.dispose();
//                Iniciando proveedor = new Iniciando(null, true);
//        proveedor.setLocationRelativeTo(null);
//        proveedor.setTitle("Iniciando Sistema");
//        proveedor.setVisible(true);

                } else {

                    JOptionPane.showMessageDialog(null, "Error al iniciar sesion ¡Vuelve a Intentarlo!");
                }

            }

        } catch (Exception e) {
        }
    }
   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_Intentos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        txt_contraseña = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        lb_Intentos.setText("jLabel6");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setText("CONTRASEÑA:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, 30));

        txt_usuario.setBorder(null);
        txt_usuario.setOpaque(false);
        getContentPane().add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 240, 20));

        txt_contraseña.setBorder(null);
        txt_contraseña.setOpaque(false);
        getContentPane().add(txt_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 240, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag_inicio/btn_iniciar_2_opt.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imag_inicio/btn_iniciar_1_opt.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 130, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag_inicio/btn_regist_2_opt.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imag_inicio/btn_regist_1_opt.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag_inicio/Sin título-1 - copia_opt.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 250, 40));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setText("USUARIO:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag_inicio/Sin título-1 - copia_opt.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 250, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/icons8_Administrator_Male_30px.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/icons8_Lock_30px.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag_inicio/LP10_opt.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 670, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        
        this.setLocation(this.getLocation().x + evt.getX() - x,this.getLocation().y + evt.getY() - y );
    }//GEN-LAST:event_formMouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        String algorithm="SHA-512";  
//        String resultado1;
//        String usuario=null;
//        String contraseña=null;
//         int sen=1;int tu=1;
//        
//        usuario=txt_usuario.getText();
//        contraseña=txt_contraseña.getText();
//       
//        resultado1=getStringMessageDigest(contraseña,algorithm);   
//       
//        
//        
//        if(usuario.length()==0 ||contraseña.length()==0) {
//            JOptionPane.showMessageDialog(this, "!Ingrese Usuario y/o Constraseña!");
//            txt_usuario.setText("");
//            txt_contraseña.setText("");
//            txt_usuario.requestFocus();
//            intentos=intentos+1;
//            lb_Intentos.setText(Integer.toString(intentos));
//
//        }
//        else 
//        {
//            try{
//               GestionarUsuario oUsuario=new GestionarUsuario();
//                
//               rs= oUsuario.Login(usuario,resultado1);
//           
//               while (rs.next()&& sen==1) {
//                    if(!rs.getString(14).equals("")){
//                        if(rs.getString(14).equals(usuario)&&rs.getString(15).equals(resultado1)) { 
//                            if(rs.getString(13).equals("ACTIVO")) { 
//                                JOptionPane.showMessageDialog(null,"Bienvenidos: Sr."+rs.getString(2)+" "+rs.getString(3),"Login Usuarios",1);
//                                sen=2;
//                            }else{
//                                JOptionPane.showMessageDialog(this, "Usuario Inactivo");
//                                sen=3;
//                            }
//                                
//                       }
//                    }else{
//                        JOptionPane.showMessageDialog(this, "Usuario no existe");
//                        sen=3;
//                    }
//                        
//                        
//
//                     
//                   break;
//                }
//               
//  
//                if(sen==1) {
//                    JOptionPane.showMessageDialog(this, "¡Usuario y/o Contraseña incorrectos!");
//                    txt_usuario.setText("");
//                    txt_contraseña.setText("");
//                    txt_usuario.requestFocus();
//                    intentos=intentos+1;
//                    lb_Intentos.setText(Integer.toString(intentos));
//                    
//                } else if(sen==3){
//                    txt_usuario.setText("");
//                    txt_contraseña.setText("");
//                    txt_usuario.requestFocus();
//                }else{
//
//                    NewJFrame mdi=new NewJFrame();
//                    mdi.show();
//                    mdi.setVisible(true);
//                    this.dispose();                    
////                    mdi.strUsuario=rs.getString(14);
////                    mdi.strIdEmpleado=rs.getString(1);
////                    mdi.strNombreEmpleado = rs.getString(2) +" "+rs.getString(3);
////                   
////                    mdi.intEstado=1; 
////                    
//                    
//                }
//
//            } catch (Exception ex) {
//                JOptionPane.showMessageDialog(this,ex.getMessage());
//                System.out.println(ex.getMessage());
//            }
//        }
//        
//        if(intentos==3){
//            this.dispose();
//        }
//        

            ValidarAcceso();
                                                 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         jDlg_Registrarse reg = new jDlg_Registrarse(null, true);
        reg.setLocationRelativeTo(null);
//        reg.setTitle("Nuevo Cliente");
        reg.setVisible(true);
      
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
//                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                }
                catch(Exception e){
                    
                }
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lb_Intentos;
    private javax.swing.JPasswordField txt_contraseña;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
