/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Gestionar_Ventas;

import Componentes.GenerarReporte;
import Componentes.conectar;
import Metodos.Conectar;

import java.awt.Frame; 
import java.awt.event.ActionEvent; 
import javax.swing.JButton; 
import javax.swing.JDialog; 
import javax.swing.JInternalFrame; 
import javax.swing.JTextField;

import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author fernando
 */
public class dlgVentaRecibo extends javax.swing.JDialog {
    private Connection connection=new conectar().conexion();
    static ResultSet rs=null;
    static ResultSet rsTotal=null;
    DefaultTableModel dtm=new DefaultTableModel();
    String criterio,busqueda;
    String Total;
    String idventa;
    String id[]=new String[50];
    static int intContador;
    /**
     * Creates new form dlgVentaRecibo1
     */
    public dlgVentaRecibo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        obtenerUltimoIdVenta();
        txtDocumentoVenta.setVisible(true);
        
        //---------------------ANCHO Y ALTO DEL FORM----------------------
//        this.setSize(400, 205);
    }
    //-----------------------------------------------------------------------------------------------
//--------------------------------------METODOS--------------------------------------------------
//-----------------------------------------------------------------------------------------------
    void obtenerUltimoIdVenta(){
                  try{
            String dato [] = new String [1];
            Conectar miconexion = new Conectar();
            String consultasql = "select max(idVFactura) from ventafactura";
//            String consultasql = "SELECT * FROM `ventafactura` WHERE `idVFactura`=5";
            ResultSet rs = miconexion.consulta(consultasql);  
            
            while(rs.next()){       //recorre el resultset mientras tenga algun dato
                for (int j=0; j<dato.length; j++){  //RECORRE HORINZONTALMENTE
                    dato[j]= rs.getString(j+1);
                }
                txtDocumentoVenta.setText(rs.getString(1));
                
                           }   
        }
         catch(Exception e){
           //e.toString() es para que te mustre el error si lo tenes 
           JOptionPane.showMessageDialog(null, e.toString()); 
        }
        
    }
    
    

        public void llamarReporteFactura() {
        GenerarReporte gr;
        gr = new GenerarReporte();
        int codF = Integer.parseInt(dlgVentaRecibo.txtDocumentoVenta.getText());
        gr.MostrarReporteConParametro("src/Reporte_Ventas/Ventas.jasper", "Factura de Venta", codF);
        gr.cerrar();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVerRecibo = new javax.swing.JButton();
        txtDocumentoVenta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        btnVerRecibo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-reporte_opt.png"))); // NOI18N
        btnVerRecibo.setToolTipText("Ver Comprobante");
        btnVerRecibo.setBorderPainted(false);
        btnVerRecibo.setContentAreaFilled(false);
        btnVerRecibo.setFocusPainted(false);
        btnVerRecibo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-reporte_opt (1)_1.png"))); // NOI18N
        btnVerRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerReciboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(txtDocumentoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnVerRecibo)
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(txtDocumentoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnVerRecibo)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerReciboActionPerformed
        llamarReporteFactura();
        
//        this.dispose();
        /*       if(txtDocumentoVenta.getText().equals("FACTURA")){
            Map p=new HashMap();
            p.put("busqueda", idventa);
            //            String imagen="C:/Users/Edgar/Desktop/Proyecto_Casita/Sistema_Casita/src/Iconos/casita.png";
            //            p.put("imagen", this.getClass().getResourceAsStream(imagen));

            JasperReport report;
            JasperPrint print;

            try{
                report=JasperCompileManager.compileReport(new File("").getAbsolutePath()+ "/src/Reportes/RptVentaFactura.jrxml");
                print=JasperFillManager.fillReport(report, p,connection);
                JasperViewer view=new JasperViewer(print,false);
                view.setTitle("Reporte de Venta");
                view.setVisible(true);
            }catch(JRException e){
                e.printStackTrace();
            }
        }else if(txtDocumentoVenta.getText().equals("BOLETA")){
            Map p=new HashMap();
            p.put("busqueda", idventa);
            JasperReport report;
            JasperPrint print;
            try{
                report=JasperCompileManager.compileReport(new File("").getAbsolutePath()+ "/src/Reportes/RptVentaBoleta.jrxml");
                print=JasperFillManager.fillReport(report, p,connection);
                JasperViewer view=new JasperViewer(print,false);
                view.setTitle("Reporte de Venta");
                view.setVisible(true);
            }catch(JRException e){
                e.printStackTrace();
            }
        }else if(txtDocumentoVenta.getText().equals("TICKET")){
            Map p=new HashMap();
            p.put("busqueda", idventa);
            JasperReport report;
            JasperPrint print;
            try{
                report=JasperCompileManager.compileReport(new File("").getAbsolutePath()+ "/src/Reportes/RptVentaTicket.jrxml");
                print=JasperFillManager.fillReport(report, p,connection);
                JasperViewer view=new JasperViewer(print,false);
                view.setTitle("Reporte de Venta");
                view.setVisible(true);
            }catch(JRException e){
                e.printStackTrace();
            }
        }
*/
        
    }//GEN-LAST:event_btnVerReciboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgVentaRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgVentaRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgVentaRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgVentaRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgVentaRecibo dialog = new dlgVentaRecibo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerRecibo;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField txtDocumentoVenta;
    // End of variables declaration//GEN-END:variables
}
