/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gestiona_articulo;

import Clases.Marca;
import Clases.Proveedor;
import Clases.Rubro;
import Clases.Tipo;
import Componentes.Mensajes;
import Metodos.CargarCombo;
import Metodos.CargarTabla;
import Metodos.Conectar;
import Metodos.JItem;
import Metodos.Leer;
import Metodos.gestionarArticulo;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaston
 */
public class JDlg_AgregarMarca extends javax.swing.JDialog {

    DefaultTableModel model;
    /**
     * Creates new form JDlg_AgregarMarca
     */
    public JDlg_AgregarMarca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       this.setLocationRelativeTo(null);
    }

    void tablaMarca(){
        // Genera espacion entre las columnas 
         tabla_Marca.getColumnModel().getColumn(0).setPreferredWidth(50);
         tabla_Marca.getColumnModel().getColumn(1).setPreferredWidth(200);
         
     } 
    
    Marca miMarca = new Marca();
    
   void  actualizartabla(String valor){
       Leer miLeer = new Leer();
       String Titulos[]={"IdMarca","Nombre Marca "};    
        Marca []miMarca = miLeer.leer_marca();
        
        CargarTabla micargatabla = new CargarTabla ();  
        
         tabla_Marca= micargatabla.cargar_tabla_Marca(tabla_Marca, miMarca, Titulos);
          tablaMarca();
       
   }
   
   void id(){
//       Guardar.setEnabled(true);
//        txt_nombMarca.setEnabled(true);
        try{
            String dato [] = new String [1];
            Conectar miconexion = new Conectar();
            String consultasql = "select max(idMarca)+1 from marca";
            ResultSet rs = miconexion.consulta(consultasql);

            while(rs.next()){       //recorre el resultset mientras tenga algun dato
                for (int j=0; j<dato.length; j++){  //RECORRE HORINZONTALMENTE
                    dato[j]= rs.getString(j+1);
                }
                lblcodigo.setText(rs.getString(1));

            }
        }
        catch(Exception e){
            //e.toString() es para que te mustre el error si lo tenes
            JOptionPane.showMessageDialog(null, e.toString());
        }
        txt_nombMarca.setText("");
    }
//     void actualizartabla(String valor){
//    String mostrar="Select * from Marca order by mar_codigo";
//    String titulos[] = {"Cod Marca", "Descripción"};
//    String []Registros=new String[5];
//    model = new DefaultTableModel(null,titulos);
//  
//        try {
//              Statement st = cn.createStatement();
//              ResultSet rs = st.executeQuery(mostrar);
//              while(rs.next())
//              {
//                  Registros[0]= rs.getString("mar_codigo");
//                  Registros[1]= rs.getString("mar_nombre");
//                       model.addRow(Registros);
//              }
//              grillaMarca.setModel(model);
//              
//        } catch (SQLException ex) {
//            Logger.getLogger(iFArticulos.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    
//  }
     void limpiarCampos()
    {
        //jLabel2.setText("");
        txt_nombMarca.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblcodigo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbo_rubro = new javax.swing.JComboBox<>();
        txt_nombMarca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Marca = new javax.swing.JTable();
        Bto_agregarTipo = new javax.swing.JButton();
        bto_modificarTipo = new javax.swing.JButton();
        bto_salir1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setOpaque(false);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Codigo:");

        lblcodigo.setForeground(new java.awt.Color(255, 255, 255));
        lblcodigo.setText("0");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Rubro:");

        cbo_rubro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txt_nombMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nombMarcaKeyReleased(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre de Marca:");

        tabla_Marca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_Marca.setSelectionBackground(new java.awt.Color(255, 0, 0));
        tabla_Marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_MarcaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_Marca);

        Bto_agregarTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-guardar_opt (1).png"))); // NOI18N
        Bto_agregarTipo.setToolTipText("Guardar");
        Bto_agregarTipo.setBorderPainted(false);
        Bto_agregarTipo.setContentAreaFilled(false);
        Bto_agregarTipo.setFocusPainted(false);
        Bto_agregarTipo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-guardar_opt.png"))); // NOI18N
        Bto_agregarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bto_agregarTipoActionPerformed(evt);
            }
        });

        bto_modificarTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-actualizar_opt.png"))); // NOI18N
        bto_modificarTipo.setToolTipText("Modificar");
        bto_modificarTipo.setBorderPainted(false);
        bto_modificarTipo.setContentAreaFilled(false);
        bto_modificarTipo.setFocusPainted(false);
        bto_modificarTipo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-actualizar_opt (1).png"))); // NOI18N
        bto_modificarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_modificarTipoActionPerformed(evt);
            }
        });

        bto_salir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-atras_opt.png"))); // NOI18N
        bto_salir1.setToolTipText("Salir");
        bto_salir1.setBorderPainted(false);
        bto_salir1.setContentAreaFilled(false);
        bto_salir1.setFocusPainted(false);
        bto_salir1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-atras_opt (1).png"))); // NOI18N
        bto_salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_salir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(7, 7, 7)
                        .addComponent(lblcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nombMarca)
                            .addComponent(cbo_rubro, 0, 290, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(316, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Bto_agregarTipo, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bto_modificarTipo, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bto_salir1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblcodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbo_rubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nombMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(140, Short.MAX_VALUE)
                    .addComponent(Bto_agregarTipo)
                    .addGap(18, 18, 18)
                    .addComponent(bto_modificarTipo)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(bto_salir1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_ABM/orig_60533_1.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 450, Short.MAX_VALUE)
                    .addGap(4, 4, 4)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 447, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        DefaultComboBoxModel miDefaultCombo = new DefaultComboBoxModel();

        CargarCombo miCargar = new CargarCombo();
        Leer miLeer = new Leer();
        Rubro[] miRubro = miLeer.leer_rubros();

        miDefaultCombo = miCargar.cargar_combo_rubro(miDefaultCombo, miRubro);

        cbo_rubro.setModel(miDefaultCombo);

        cbo_rubro.setSelectedIndex(-1);

        String Titulos[] = {"IdMarca", "Nombre Marca "};
        Marca[] miMarca1 = miLeer.leer_marca();
        CargarTabla micargatabla = new CargarTabla();
        
        tabla_Marca = micargatabla.cargar_tabla_Marca(tabla_Marca, miMarca1, Titulos);
        tablaMarca();
        
    }//GEN-LAST:event_formWindowOpened

    private void tabla_MarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_MarcaMouseClicked
        
//        lblcodigo.setEnabled(true);
//        txt_nombMarca.setEnabled(true);

        Marca filaMarca = new Marca();
        int filamodificar= tabla_Marca.getSelectedRow();
        if(filamodificar>=0)
        {
            lblcodigo.setText(tabla_Marca.getValueAt(filamodificar, 0).toString());
            txt_nombMarca.setText(tabla_Marca.getValueAt(filamodificar, 1).toString());
        }
        else
        {
            JOptionPane.showMessageDialog(this,"No ha seleccionado ");
        }
    }//GEN-LAST:event_tabla_MarcaMouseClicked
    
    private void txt_nombMarcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombMarcaKeyReleased

               
        String aux = txt_nombMarca.getText().toUpperCase();
        txt_nombMarca.setText(aux);
        
    }//GEN-LAST:event_txt_nombMarcaKeyReleased

    private void Bto_agregarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bto_agregarTipoActionPerformed

        Leer miLeer = new Leer();
        gestionarArticulo GuardarMarca = new gestionarArticulo();
       
        if (txt_nombMarca.getText().isEmpty()) //VALIDACIONES
        {
            JOptionPane.showMessageDialog(null, "Igrese NOMBRE MARCA ", "Error: Datos Incompletos", JOptionPane.ERROR_MESSAGE);

        } else {

//        miMarca.setCodMarca(Integer.parseInt(lblcodigo.getText()));
            miMarca.setDetalleMarca(txt_nombMarca.getText().toUpperCase());
            
            int pos = cbo_rubro.getSelectedIndex();
             if (pos >=0) {
                    Object obj = cbo_rubro.getItemAt(pos);
                    JItem item = new JItem(obj);         
                    
                    miMarca.setIdRubro((Integer)item.getItemData());

             }

            GuardarMarca.GuardarMarca(miMarca);
            actualizartabla(" ");
           
//
//            String Titulos[] = {"IdMarca", "Nombre Marca "};
//            Marca[] miMarca1 = miLeer.leer_marca();
//            CargarTabla micargatabla = new CargarTabla();
//            tablaMarca();
             Mensajes.informacion("Marca Registrada");
//            tabla_Marca = micargatabla.cargar_tabla_Marca(tabla_Marca, miMarca1, Titulos);
            limpiarCampos();
            
       

        }

    }//GEN-LAST:event_Bto_agregarTipoActionPerformed

    private void bto_modificarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_modificarTipoActionPerformed
        
         gestionarArticulo modMarca = new gestionarArticulo();
///        Modificar.setEnabled(false);
       
//        txt_nombMarca.setEnabled(false);

        miMarca.setIdMarca(Integer.parseInt(lblcodigo.getText().trim()));
        miMarca.setDetalleMarca(txt_nombMarca.getText().toUpperCase());

        modMarca.modificarMarca(miMarca);
        limpiarCampos();
       
        actualizartabla("");
         Mensajes.informacion("Marca Actualizado");
    }//GEN-LAST:event_bto_modificarTipoActionPerformed

    private void bto_salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_salir1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_bto_salir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlg_AgregarMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlg_AgregarMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlg_AgregarMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlg_AgregarMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlg_AgregarMarca dialog = new JDlg_AgregarMarca(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bto_agregarTipo;
    private javax.swing.JButton bto_modificarTipo;
    private javax.swing.JButton bto_salir1;
    private javax.swing.JComboBox<String> cbo_rubro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JTable tabla_Marca;
    private javax.swing.JTextField txt_nombMarca;
    // End of variables declaration//GEN-END:variables
}
