/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gestiona_articulo;

import Clases.Marca;
import Clases.Rubro;
import Clases.Tipo;
import Componentes.Mensajes;
import Metodos.CargarCombo;
import Metodos.CargarTabla;
import Metodos.Conectar;
import Metodos.JItem;
import Metodos.Leer;
import Metodos.gestionarArticulo;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Gaston
 */
public class JDlg_AgregarTipo extends javax.swing.JDialog {

    /**
     * Creates new form JDlg_AgregarMarca
     */
    public JDlg_AgregarTipo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }
void tablaTipo(){
        // Genera espacion entre las columnas 
         tabla_tipo.getColumnModel().getColumn(0).setPreferredWidth(50);
         tabla_tipo.getColumnModel().getColumn(1).setPreferredWidth(200);
         
     } 
    
    Tipo miTipo = new Tipo();
    
   void  actualizartabla(String valor){
       Leer miLeer = new Leer();
       String Titulos[]={"IdTipo","Nombre Tipo "};    
        Tipo []miTipo = miLeer.leer_tipo();
        
        CargarTabla micargatabla = new CargarTabla ();  
        
         tabla_tipo= micargatabla.cargar_tabla_Tipo(tabla_tipo, miTipo, Titulos);
          tablaTipo();
       
   }
    void limpiarCampos()
    {
        //jLabel2.setText("");
        txt_nombTipo.setText("");
    }
   
   void id(){
//       Guardar.setEnabled(true);
//        txt_nombMarca.setEnabled(true);
        try{
            String dato [] = new String [1];
            Conectar miconexion = new Conectar();
            String consultasql = "select max(idTipo)+1 from tipo";
            ResultSet rs = miconexion.consulta(consultasql);

            while(rs.next()){       //recorre el resultset mientras tenga algun dato
                for (int j=0; j<dato.length; j++){  //RECORRE HORINZONTALMENTE
                    dato[j]= rs.getString(j+1);
                }
                lblcodigo.setText(rs.getString(1));

            }
        }
        catch(Exception e){
            //e.toString() es para que te mustre el error si lo tenes
            JOptionPane.showMessageDialog(null, e.toString());
        }
        txt_nombTipo.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_tipo = new javax.swing.JTable();
        Bto_agregarTipo = new javax.swing.JButton();
        bto_salir = new javax.swing.JButton();
        bto_modificarTipo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbo_Marca = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txt_nombTipo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblcodigo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setOpaque(false);

        tabla_tipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_tipo.setSelectionBackground(new java.awt.Color(255, 0, 0));
        tabla_tipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_tipoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_tipo);

        Bto_agregarTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-guardar_opt (1).png"))); // NOI18N
        Bto_agregarTipo.setToolTipText("Guardar");
        Bto_agregarTipo.setBorderPainted(false);
        Bto_agregarTipo.setContentAreaFilled(false);
        Bto_agregarTipo.setFocusPainted(false);
        Bto_agregarTipo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-guardar_opt.png"))); // NOI18N
        Bto_agregarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bto_agregarTipoActionPerformed(evt);
            }
        });

        bto_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-atras_opt.png"))); // NOI18N
        bto_salir.setToolTipText("Salir");
        bto_salir.setBorderPainted(false);
        bto_salir.setContentAreaFilled(false);
        bto_salir.setFocusPainted(false);
        bto_salir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-atras_opt (1).png"))); // NOI18N
        bto_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_salirActionPerformed(evt);
            }
        });

        bto_modificarTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-actualizar_opt.png"))); // NOI18N
        bto_modificarTipo.setToolTipText("Modificar");
        bto_modificarTipo.setBorderPainted(false);
        bto_modificarTipo.setContentAreaFilled(false);
        bto_modificarTipo.setFocusPainted(false);
        bto_modificarTipo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-actualizar_opt (1).png"))); // NOI18N
        bto_modificarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_modificarTipoActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Marca:");

        cbo_Marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre de Tipo:");

        txt_nombTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nombTipoKeyReleased(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Codigo:");

        lblcodigo.setForeground(new java.awt.Color(255, 255, 255));
        lblcodigo.setText("2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bto_agregarTipo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bto_modificarTipo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bto_salir, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(txt_nombTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbo_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(lblcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbo_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nombTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Bto_agregarTipo)
                        .addGap(18, 18, 18)
                        .addComponent(bto_modificarTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bto_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_ABM/orig_60533_1.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 412, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bto_agregarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bto_agregarTipoActionPerformed
        
        Leer miLeer = new Leer();
        gestionarArticulo GuardarMarca = new gestionarArticulo();
       
        if (txt_nombTipo.getText().isEmpty()) //VALIDACIONES
        {
            JOptionPane.showMessageDialog(null, "Igrese NOMBRE TIPO ", "Error: Datos Incompletos", JOptionPane.ERROR_MESSAGE);

        } else {

//            miTipo.setCodMarca(Integer.parseInt(lblcodigo.getText()));
            miTipo.setDetalle_tipo(txt_nombTipo.getText().toUpperCase());
            
            int pos = cbo_Marca.getSelectedIndex();
             if (pos >=0) {
                    Object obj = cbo_Marca.getItemAt(pos);
                    JItem item = new JItem(obj);         
                    
                    miTipo.setIdMarca((Integer)item.getItemData());

             }

            GuardarMarca.GuardarTipo(miTipo);
            actualizartabla(" ");
           
//
//            String Titulos[] = {"IdMarca", "Nombre Marca "};
//            Marca[] miMarca1 = miLeer.leer_marca();
//            CargarTabla micargatabla = new CargarTabla();
//            tablaMarca();
             Mensajes.informacion("tipo Registrado");
//            tabla_Marca = micargatabla.cargar_tabla_Marca(tabla_Marca, miMarca1, Titulos);
            limpiarCampos();
            
       

        }
        
    }//GEN-LAST:event_Bto_agregarTipoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

         DefaultComboBoxModel miDefaultCombo = new DefaultComboBoxModel();

        CargarCombo miCargar = new CargarCombo();
        Leer miLeer = new Leer();
        Marca[] mimarca = miLeer.leer_marca();

        miDefaultCombo = miCargar.cargar_combo_marca(miDefaultCombo, mimarca);

        cbo_Marca.setModel(miDefaultCombo);

        cbo_Marca.setSelectedIndex(-1);

        String Titulos[] = {"IdTipo", "Nombre Tipo "};
        Tipo[] miTipo1 = miLeer.leer_tipo();
        CargarTabla micargatabla = new CargarTabla();
        
        tabla_tipo = micargatabla.cargar_tabla_Tipo(tabla_tipo, miTipo1, Titulos);
        tablaTipo();
    }//GEN-LAST:event_formWindowOpened

    private void tabla_tipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_tipoMouseClicked
       
        int filamodificar = tabla_tipo.getSelectedRow();
        if (filamodificar >= 0) {
            lblcodigo.setText(tabla_tipo.getValueAt(filamodificar, 0).toString());
            txt_nombTipo.setText(tabla_tipo.getValueAt(filamodificar, 1).toString());
        } else {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ");
        }
    }//GEN-LAST:event_tabla_tipoMouseClicked

    private void bto_modificarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_modificarTipoActionPerformed

      gestionarArticulo modTipo = new gestionarArticulo();
///        Modificar.setEnabled(false);
       
//        txt_nombTipo.setEnabled(false);

        miTipo.setIdTipo(Integer.parseInt(lblcodigo.getText().trim()));
        miTipo.setDetalle_tipo(txt_nombTipo.getText().toUpperCase());

        modTipo.modificarTipo(miTipo);
        limpiarCampos();
       
        actualizartabla("");
         Mensajes.informacion("Tipo Actualizado");
    }//GEN-LAST:event_bto_modificarTipoActionPerformed

    private void bto_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_bto_salirActionPerformed

    private void txt_nombTipoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombTipoKeyReleased

             
        String aux = txt_nombTipo.getText().toUpperCase();
        txt_nombTipo.setText(aux);
        
    }//GEN-LAST:event_txt_nombTipoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlg_AgregarTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlg_AgregarTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlg_AgregarTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlg_AgregarTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlg_AgregarTipo dialog = new JDlg_AgregarTipo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bto_agregarTipo;
    private javax.swing.JButton bto_modificarTipo;
    private javax.swing.JButton bto_salir;
    private javax.swing.JComboBox<String> cbo_Marca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JTable tabla_tipo;
    private javax.swing.JTextField txt_nombTipo;
    // End of variables declaration//GEN-END:variables
}
