/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gestiona_articulo;

import Clases.Marca;
import Clases.Rubro;
import Componentes.Mensajes;
import Metodos.CargarCombo;
import Metodos.CargarTabla;
import Metodos.Conectar;
import Metodos.JItem;
import Metodos.Leer;
import Metodos.gestionarArticulo;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaston
 */
public class JDlg_AgregarRubro extends javax.swing.JDialog {

    DefaultTableModel model;
    /**
     * Creates new form JDlg_AgregarMarca
     */
    public JDlg_AgregarRubro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

         void tablaRubro(){
        // Genera espacion entre las columnas 
         tabla_rubro.getColumnModel().getColumn(0).setPreferredWidth(50);
         tabla_rubro.getColumnModel().getColumn(1).setPreferredWidth(200);
         
     } 
    
    Rubro miRubro = new Rubro();
    
   void  actualizartabla(String valor){
       Leer miLeer = new Leer();
       String Titulos[]={"IdRubro","Nombre Rubro "};    
        Rubro []miRubro = miLeer.leer_rubros();
        
        CargarTabla micargatabla = new CargarTabla ();  
        
         tabla_rubro= micargatabla.cargar_tabla_Rubro(tabla_rubro, miRubro, Titulos);
          tablaRubro();
       
   }
   
   void id(){
//       Guardar.setEnabled(true);
//        txt_nombMarca.setEnabled(true);
        try{
            String dato [] = new String [1];
            Conectar miconexion = new Conectar();
            String consultasql = "select max(idRubro)+1 from rubro";
            ResultSet rs = miconexion.consulta(consultasql);

            while(rs.next()){       //recorre el resultset mientras tenga algun dato
                for (int j=0; j<dato.length; j++){  //RECORRE HORINZONTALMENTE
                    dato[j]= rs.getString(j+1);
                }
                lblcodigo.setText(rs.getString(1));

            }
        }
        catch(Exception e){
            //e.toString() es para que te mustre el error si lo tenes
            JOptionPane.showMessageDialog(null, e.toString());
        }
        txt_nombRubro.setText("");
    }
//     void actualizartabla(String valor){
//    String mostrar="Select * from Marca order by mar_codigo";
//    String titulos[] = {"Cod Marca", "Descripción"};
//    String []Registros=new String[5];
//    model = new DefaultTableModel(null,titulos);
//  
//        try {
//              Statement st = cn.createStatement();
//              ResultSet rs = st.executeQuery(mostrar);
//              while(rs.next())
//              {
//                  Registros[0]= rs.getString("mar_codigo");
//                  Registros[1]= rs.getString("mar_nombre");
//                       model.addRow(Registros);
//              }
//              grillaMarca.setModel(model);
//              
//        } catch (SQLException ex) {
//            Logger.getLogger(iFArticulos.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    
//  }
     void limpiarCampos()
    {
        //jLabel2.setText("");
        txt_nombRubro.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblcodigo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombRubro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_rubro = new javax.swing.JTable();
        Bto_agregarTipo = new javax.swing.JButton();
        bto_modificarTipo = new javax.swing.JButton();
        bto_salir1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setOpaque(false);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Codigo:");

        lblcodigo.setForeground(new java.awt.Color(255, 255, 255));
        lblcodigo.setText("2");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre de Rubro:");

        txt_nombRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombRubroActionPerformed(evt);
            }
        });
        txt_nombRubro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nombRubroKeyReleased(evt);
            }
        });

        tabla_rubro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_rubro.setSelectionBackground(new java.awt.Color(255, 0, 0));
        tabla_rubro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_rubroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_rubro);

        Bto_agregarTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-guardar_opt (1).png"))); // NOI18N
        Bto_agregarTipo.setToolTipText("Guardar");
        Bto_agregarTipo.setBorderPainted(false);
        Bto_agregarTipo.setContentAreaFilled(false);
        Bto_agregarTipo.setFocusPainted(false);
        Bto_agregarTipo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-guardar_opt.png"))); // NOI18N
        Bto_agregarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bto_agregarTipoActionPerformed(evt);
            }
        });

        bto_modificarTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-actualizar_opt.png"))); // NOI18N
        bto_modificarTipo.setToolTipText("Modificar");
        bto_modificarTipo.setBorderPainted(false);
        bto_modificarTipo.setContentAreaFilled(false);
        bto_modificarTipo.setFocusPainted(false);
        bto_modificarTipo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-actualizar_opt (1).png"))); // NOI18N
        bto_modificarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_modificarTipoActionPerformed(evt);
            }
        });

        bto_salir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-atras_opt.png"))); // NOI18N
        bto_salir1.setToolTipText("Salir");
        bto_salir1.setBorderPainted(false);
        bto_salir1.setContentAreaFilled(false);
        bto_salir1.setFocusPainted(false);
        bto_salir1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Botones/x128-atras_opt (1).png"))); // NOI18N
        bto_salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_salir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_nombRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bto_salir1)
                            .addComponent(bto_modificarTipo)
                            .addComponent(Bto_agregarTipo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(lblcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Bto_agregarTipo)
                        .addGap(18, 18, 18)
                        .addComponent(bto_modificarTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bto_salir1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_ABM/orig_60533_1.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabla_rubroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_rubroMouseClicked
        
        
//        lblcodigo.setEnabled(true);
//        txt_nombMarca.setEnabled(true);

        
        int filamodificar= tabla_rubro.getSelectedRow();
        if(filamodificar>=0)
        {
            lblcodigo.setText(tabla_rubro.getValueAt(filamodificar, 0).toString());
            txt_nombRubro.setText(tabla_rubro.getValueAt(filamodificar, 1).toString());
        }
        else
        {
            JOptionPane.showMessageDialog(this,"No ha seleccionado ");
        }
    }//GEN-LAST:event_tabla_rubroMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        DefaultComboBoxModel miDefaultCombo = new DefaultComboBoxModel();

        CargarCombo miCargar = new CargarCombo();
        Leer miLeer = new Leer();
   
        String Titulos[] = {"IdRubro", "Nombre Rubro "};
        Rubro[] miRubro1 = miLeer.leer_rubros();
        CargarTabla micargatabla = new CargarTabla();
        
        tabla_rubro = micargatabla.cargar_tabla_Rubro(tabla_rubro, miRubro1, Titulos);
        tablaRubro();
    }//GEN-LAST:event_formWindowOpened

    private void txt_nombRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombRubroActionPerformed
         
       
    }//GEN-LAST:event_txt_nombRubroActionPerformed

    private void txt_nombRubroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombRubroKeyReleased

       
        String aux = txt_nombRubro.getText().toUpperCase();
        txt_nombRubro.setText(aux);
        
        
    }//GEN-LAST:event_txt_nombRubroKeyReleased

    private void Bto_agregarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bto_agregarTipoActionPerformed

          Leer miLeer = new Leer();
        gestionarArticulo GuardarMarca = new gestionarArticulo();
      
        if (txt_nombRubro.getText().isEmpty()) //VALIDACIONES
        {
            JOptionPane.showMessageDialog(null, "Igrese NOMBRE RUBRO ", "Error: Datos Incompletos", JOptionPane.ERROR_MESSAGE);

        } else {

//        miMarca.setCodMarca(Integer.parseInt(lblcodigo.getText()));
            miRubro.setNombreRubro(txt_nombRubro.getText().toUpperCase());
            
            

            GuardarMarca.GuardarRubro(miRubro);
            actualizartabla(" ");
           
//
//            String Titulos[] = {"IdMarca", "Nombre Marca "};
//            Marca[] miMarca1 = miLeer.leer_marca();
//            CargarTabla micargatabla = new CargarTabla();
//            tablaMarca();
             Mensajes.informacion("Marca Registrada");
//            tabla_Marca = micargatabla.cargar_tabla_Marca(tabla_Marca, miMarca1, Titulos);
            limpiarCampos();
            
       

        }

    }//GEN-LAST:event_Bto_agregarTipoActionPerformed

    private void bto_modificarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_modificarTipoActionPerformed

        
         gestionarArticulo modRubro = new gestionarArticulo();
///        Modificar.setEnabled(false);
       
        txt_nombRubro.setEnabled(false);

        miRubro.setIdRubro(Integer.parseInt(lblcodigo.getText().trim()));
        miRubro.setNombreRubro(txt_nombRubro.getText().toUpperCase());

        modRubro.modificarRubro(miRubro);
        limpiarCampos();
       
        actualizartabla("");
         Mensajes.informacion("Rubro Actualizado");
                 
    }//GEN-LAST:event_bto_modificarTipoActionPerformed

    private void bto_salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_salir1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_bto_salir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlg_AgregarRubro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlg_AgregarRubro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlg_AgregarRubro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlg_AgregarRubro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlg_AgregarRubro dialog = new JDlg_AgregarRubro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bto_agregarTipo;
    private javax.swing.JButton bto_modificarTipo;
    private javax.swing.JButton bto_salir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JTable tabla_rubro;
    private javax.swing.JTextField txt_nombRubro;
    // End of variables declaration//GEN-END:variables
}
