/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gestionar_Stock;

import Clases.Articulo; 
import Clases.DetalleSalidaStock;
import Clases.SalidaStock;
import com.toedter.calendar.JDateChooser; 
import java.awt.Frame; 
import java.awt.event.ActionEvent; 
import java.awt.event.MouseEvent; 
import javax.swing.JButton; 
import javax.swing.JComboBox; 
import javax.swing.JDialog; 
import javax.swing.JLabel; 
import javax.swing.JMenuBar; 
import javax.swing.JPanel; 
import javax.swing.JScrollPane; 
import javax.swing.JTable; 
import javax.swing.JTextField;

import Componentes.Fecha;
import Componentes.Mensajes;
import Componentes.validarCampos;
import Metodos.Actualizar;
import Metodos.CargarCombo;
import Metodos.Conectar;
import Metodos.buscarid;
import Metodos.llamarArticulo;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luca
 */
public class dlgModificarStock extends javax.swing.JDialog {
DefaultTableModel objtabla = new DefaultTableModel();
    /**
     * Creates new form dlgSalidaMercaderia
     */
    public dlgModificarStock(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        idSalida();
        Date date=new Date();
        String format=new String("dd/MM/yyyy");
        SimpleDateFormat formato=new SimpleDateFormat(format);
        txtFecha.setDate(date);
        String detalleSalida[] = {"Codigo","Descripcion","Cantidad  "};
        objtabla.setColumnIdentifiers(detalleSalida);
        grillaSalidaMerc.setModel(objtabla);
        combomotivo();
        tablaarticulo();

        

    }
 CargarCombo cargarcmb=new CargarCombo();
 Articulo miArt = new Articulo();
 buscarid id = new buscarid();
 


 
        void combomotivo(){
         String cons="Select detallemotivo from motivo_stock";
         cargarcmb.cargacombo(cmbmotivo, cons);
         //cmbrubro.setSelectedIndex(-1);
       }
        
  void tablaarticulo(){
        // Genera espacion entre las columnas 
        grillaSalidaMerc.getColumnModel().getColumn(0).setPreferredWidth(50);
        grillaSalidaMerc.getColumnModel().getColumn(1).setPreferredWidth(250);
        grillaSalidaMerc.getColumnModel().getColumn(2).setPreferredWidth(70);


        
     } 
  
      void idSalida(){
                   try{
            String dato [] = new String [1];
            Conectar miconexion = new Conectar();
            String consultasql = "select max(idsalida)+1 from salida_stock";
            ResultSet rs = miconexion.consulta(consultasql);  
            
            while(rs.next()){       //recorre el resultset mientras tenga algun dato
                for (int j=0; j<dato.length; j++){  //RECORRE HORINZONTALMENTE
                    dato[j]= rs.getString(j+1);
                }
                lblSalida.setText(rs.getString(1));
                
                     
       // en caso de ser el primer articulo que vamos a cargar, se fija que la table este vacia y genera el 1
       //como id principal, en el caso contrario busca el ultimo y le suma 1
             if(rs.getString(1)==null){
             lblSalida.setText("1");
            }
            else{
             /*
                 j=Integer.parseInt(c);
                 GenerarNumero gen= new GenerarNumero();
                 gen.generar(j);
                 txtid.setText(gen.serie());
                
            */
            }
                
                           }   
        }
         catch(Exception e){
           //e.toString() es para que te mustre el error si lo tenes 
           JOptionPane.showMessageDialog(null, e.toString()); 
        }
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSalida = new javax.swing.JLabel();
        lblSalida1 = new javax.swing.JLabel();
        txtFecha = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtArt = new javax.swing.JTextField();
        BuscarArticulos = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmbmotivo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        grillaSalidaMerc = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowInddex, int celIndex)
            {
                return false;
            }
        };
        Eliminar = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("*Fecha:");

        jLabel2.setText("MODIFICACION DE STOCK");

        lblSalida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSalida.setText("jLabel4");

        lblSalida1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSalida1.setText("N°");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSalida1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(lblSalida)
                        .addComponent(lblSalida1)))
                .addGap(17, 17, 17))
        );

        jLabel3.setText("*Articulo :");

        txtArt.setEditable(false);

        BuscarArticulos.setText("F5");
        BuscarArticulos.setToolTipText("Buscar Artículo");
        BuscarArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarArticulosActionPerformed(evt);
            }
        });

        jLabel8.setText("*Motivo :");

        cmbmotivo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbmotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmotivoActionPerformed(evt);
            }
        });

        grillaSalidaMerc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        grillaSalidaMerc.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        grillaSalidaMerc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grillaSalidaMercMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grillaSalidaMerc);

        Eliminar.setText("Eliminar Linea");
        Eliminar.setToolTipText("Buscar Artículo");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Guardar.setText("Aceptar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Eliminar)
                .addGap(131, 131, 131)
                .addComponent(Guardar)
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BuscarArticulos)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbmotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarArticulos)
                    .addComponent(jLabel8)
                    .addComponent(cmbmotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eliminar)
                    .addComponent(Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarArticulosActionPerformed
           try {
            JDlg_BuscarArticuloModStock dbp = new JDlg_BuscarArticuloModStock(null, true);
            dbp.setLocationRelativeTo(null);
            dbp.setTitle("Buscar Articulo");
            dbp.setVisible(true);
        } catch (Exception e) {
            Mensajes.informacion("No hay conexión con el servidor");
        } 
    }//GEN-LAST:event_BuscarArticulosActionPerformed

    private void cmbmotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmotivoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbmotivoActionPerformed

    private void grillaSalidaMercMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grillaSalidaMercMouseClicked

    }//GEN-LAST:event_grillaSalidaMercMouseClicked

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
       int fila = grillaSalidaMerc.getSelectedRow();
    if(fila>=0)
    {
        int seleccion= JOptionPane.showOptionDialog(this, "¿ESTA SEGURO?", "CONFIRMAR BAJA", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"ACEPTAR","CANCELAR"},"ACEPTAR");
        objtabla.removeRow(fila);
    }
    else
    {
        JOptionPane.showMessageDialog(null, "No Selecciono ninguna fila");
    }      

    }//GEN-LAST:event_EliminarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        gestionarSalida guardSalida = new gestionarSalida();
        
        Actualizar actualizarStock =new Actualizar();
        llamarArticulo llamArt= new llamarArticulo();
         SalidaStock misalida = new SalidaStock();
        DetalleSalidaStock detStock = new DetalleSalidaStock();
        buscarid id = new buscarid();
        Articulo art =new Articulo();
          
        if(txtFecha.getDate().equals(evt) )                                                                                                   //VALIDACIONES
       { 
           JOptionPane.showMessageDialog(null,"Igrese FECHA DE LA OPERACION ","Error: Datos Incompletos",JOptionPane.ERROR_MESSAGE);
      
       }
       
       else if(txtArt.getText().isEmpty() ) 
       { 
           JOptionPane.showMessageDialog(null,"Selecciona un ARTICULO ","Error: Datos Incompletos",JOptionPane.ERROR_MESSAGE);
      
       }
    
       else{
           // detalle salida
       misalida.setIdsalida(Integer.parseInt(lblSalida.getText()));
       misalida.setFecha(txtFecha.getDate());
       int idmotivostock = id.buscarid("idmotivo", "motivo_stock", "detallemotivo", String.valueOf(cmbmotivo.getSelectedItem()));
       misalida.setIdmotivo(idmotivostock);

       

       
       guardSalida.guardarSalida(misalida);
       
      
      
       
               ///////////////////DETALLE stock////////////////////
        for (int i=0; i < objtabla.getRowCount(); i++){
            
            detStock.setIdarticulo(Integer.parseInt(grillaSalidaMerc.getValueAt(i, 0).toString()));
            detStock.setIdsalida(Integer.parseInt(lblSalida.getText()));
            detStock.setCantidad(Integer.parseInt(grillaSalidaMerc.getValueAt(i, 2).toString()));
            
            //Actualizar Stock
            art=llamArt.llamarArt("idarticulo", grillaSalidaMerc.getValueAt(i, 0).toString()); //llama al articulo
            actualizarStock.actualizarproducto(art,Integer.parseInt(grillaSalidaMerc.getValueAt(i, 2).toString()) );// Manda articulo y cantidad
            
            guardSalida.detalleSalida(detStock);
        }
        
        // VER COMO VOLVER A ABRIR UN INTERNALFRAME DE VUELTA // CON LOS JDIALOG SE PUEDE.
        int seleccion= JOptionPane.showOptionDialog(this, "Operacion Guardada con exito! ¿REALIZAR OTRA OPERACION?", "Atecion", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"SI","NO, SALIR"},"SI");
        if(seleccion!=-1)
        {
            if((seleccion +1)==1){
                this.dispose();
               dlgModificarStock salida = new dlgModificarStock(null, true);
        salida.setLocationRelativeTo(null);
        salida.setTitle("Salida de Mercaderias");
        salida.setVisible(true);
        

        
            }
            else{
            
            this.dispose(); 
            }
        }
        
       
      
                }      

                
    }//GEN-LAST:event_GuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
                this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgModificarStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgModificarStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgModificarStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgModificarStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgModificarStock dialog = new dlgModificarStock(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarArticulos;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton btnSalir;
    public static javax.swing.JComboBox cmbmotivo;
    public static javax.swing.JTable grillaSalidaMerc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblSalida;
    public static javax.swing.JLabel lblSalida1;
    public static javax.swing.JTextField txtArt;
    private com.toedter.calendar.JDateChooser txtFecha;
    // End of variables declaration//GEN-END:variables
}
